In [1]:
import numpy as np
import cv2
import os
from PIL import Image

In [2]:
folder_path = 'E:/raghav/Projects/PersonalProjects/Viola-Jones_Face_Detection/Yale Face Database'
input_images = []
output_labels = []

In [3]:
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    img = Image.open(file_path).convert('L')
    img = np.array(img)
    if len(img.shape) > 2:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    output_labels.append(filename[10:])
    input_images.append(img)

In [4]:
print(input_images[0])

[[130 130 130 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [ 68  68  68 ...  68  68  68]]


In [5]:
def viewImage(image):
    cv2.imshow("view image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [6]:
viewImage(input_images[1])

In [7]:
# gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# img_array = np.array(img)

# print(np.array(input_images))

In [8]:
def Integral_image_finder(nums):
    nums = nums.astype(np.uint64)
    a, b = nums.shape
    integral_image = np.copy(nums)
    for i in range(a):
        for j in range(b):
            if i > 0:
                integral_image[i][j] += integral_image[i-1][j]
            if j > 0:
                integral_image[i][j] += integral_image[i][j-1]
            if i > 0 and j > 0:
                integral_image[i][j] -= integral_image[i-1][j-1]
    return integral_image

In [9]:
# img_int_array = Integral_image_finder(img)
# viewImage(img)

In [112]:
# img_int_array2 = cv2.integral(img_array)
normalized_integral = cv2.normalize(img_int_array, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

print()

[[     130      260      390 ...    65292    65547    65802]
 [     385      770     1155 ...   146382   146892   147402]
 [     640     1280     1920 ...   227472   228237   229002]
 ...
 [   61330   122660   183990 ... 14605584 14666486 14727477]
 [   61585   123170   184755 ... 14660577 14721734 14782980]
 [   61653   123306   184959 ... 14682201 14743426 14804740]]


In [114]:
viewImage(img_int_array)

error: OpenCV(4.8.1) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'


: 

In [37]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

In [38]:
output_labels = np.array(output_labels).reshape(-1, 1)
# output_labels = output_labels.reshape(-1, 1)
output_labels = ohe.fit_transform(output_labels).toarray()

In [63]:
# signed_number = np.int8(-5)

# # Unsigned integer
# unsigned_number = np.uint8(-5)
# print(signed_number)

In [40]:
def find_haar_feat(array, template):
    x, y, width, height = template
    feat_value = np.zeros()
    for j in range(len(array.shape[0])):
        for x in range(array.shape[1]-height):
            for y in range(array.shape[2]-width):
                feat_value[j] = array[x,y] - array[x+height, y] - array[x, y+width] + array[x+height, y+width]





SyntaxError: incomplete input (4017338526.py, line 2)