In [9]:
import numpy as np
import cv2

In [10]:
img = cv2.imread('sample images/messi.jpg')

In [11]:
def viewImage(image):
    cv2.imshow("view image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [12]:
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_array = np.array(gray_image)

In [13]:
print(np.array(img_array))

[[248 248 248 ... 244 244 244]
 [248 248 248 ... 244 244 244]
 [248 248 248 ... 244 244 244]
 ...
 [248 248 248 ... 236 235 235]
 [248 248 248 ... 236 235 235]
 [248 248 248 ... 236 235 235]]


In [14]:
# def compute_integral_image(image):
#     # Ensure the input image is a NumPy array
#     image = np.array(image, dtype=np.uint64)

#     # Get the dimensions of the input image
#     height, width = image.shape

#     # Initialize the integral image with zeros
#     integral_image = np.zeros((height, width), dtype=np.uint64)

#     # Compute the integral image
#     for y in range(height):
#         for x in range(width):
#             pixel_value = image[y, x]
#             sum_above = integral_image[y-1, x] if y > 0 else 0
#             sum_left = integral_image[y, x-1] if x > 0 else 0
#             sum_above_left = integral_image[y-1, x-1] if y > 0 and x > 0 else 0

#             integral_image[y, x] = pixel_value + sum_above + sum_left - sum_above_left

#     return integral_image

In [15]:
def Integral_image_finder(nums):
#     nums1 = nums
    nums = nums.astype(np.uint64)
    a, b = nums.shape
#     for i in range(a):
#         for j in range(b):
#             if i == 0:
#                 nums1[i][j] += nums1[i][j-1]
#             if j == 0:
#                 nums1[i][j] += nums1[i-1][j]
#             if i > 0 and j > 0:
#                 nums1[i][j] += nums1[i-1][j] + nums1[i][j-1] - nums1[i-1][j-1]
#     return nums1
    integral_image = np.copy(nums)
    for i in range(a):
        for j in range(b):
            if i > 0:
                integral_image[i][j] += integral_image[i-1][j]
            if j > 0:
                integral_image[i][j] += integral_image[i][j-1]
            if i > 0 and j > 0:
                integral_image[i][j] -= integral_image[i-1][j-1]
    return integral_image

In [16]:
img_int_array2 = cv2.integral(img_array)
normalized_integral = cv2.normalize(img_int_array2, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

print(normalized_integral)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   1   1   1]
 [  0   0   0 ...   1   1   1]
 ...
 [  0   1   1 ... 253 253 254]
 [  0   1   1 ... 253 254 254]
 [  0   1   1 ... 254 254 255]]


In [17]:
# print(img_int_array == img_int_array2)

In [18]:
cv2.imshow("View Image", normalized_integral)
cv2.waitKey(0)

# Close all OpenCV windows
cv2.destroyAllWindows()